### ISSUE TITLE
some features and fixes

### ISSUE THREAD

**Issue by gpongelli** [FirefoxMetzger/mini-extension#1]
Hi @FirefoxMetzger , thanks for this example repo, I'm approaching building with poetry and it's very useful!

I'm focusing only on shared_library example, but probably those things I'm reporting can be found also on other examples.

Just some thing to improve:
1. on README.md example, due to the ctype function definition, the correct call is `print(hello_world().decode())` because it returns `c_char_p`
2. to have `hello_world.py` a little more os-independent, the following implementation run in windows and in linux
```python
import platform
import os
import re

from ctypes import cdll, c_char_p
from pathlib import Path

# load the library using ctypes
_extension = ''
if platform.system() == ' Windows':
    _extension = 'dll'
if platform.system() == 'Linux':
    _extension = 'so'

_base_path = Path(__file__).parent.absolute().joinpath('lib')
# linux do put 'lib' as name prefix and can put the version after the extension (e.g. libhello_library.so.0.1.0 )
res = [f for f in os.listdir(_base_path) if re.search(rf'[a-z]*hello_library[a_z]*.{_extension}[.0-9]*', f)]

# just one library should be into the folder, otherwise exception is raised
lib_shared_hello = cdll.LoadLibrary(str(_base_path.joinpath(res[0])))

# expose the hello function as hello_world in python
# Note: returns a bytes object, not a python string
hello_world = lib_shared_hello.hello
hello_world.restype = c_char_p
```

Thank you to have spotted the way to build C-project into poetry-managed project!

**Comment by FirefoxMetzger** [comment]
Thanks for the feedback @gpongelli !

Yes, this would definitely be a good improvement. Could you submit a PR for it? Then I will review and merge it right away.
