### ISSUE TITLE
`setuptools.dep_util` is deprecated and will be removed soon. Alternative suggested in `setuptools.modified`.

### ISSUE THREAD

**Issue by abravalheri** [FirefoxMetzger/mini-extension#5]
https://github.com/FirefoxMetzger/mini-extension/blob/283a5c87c51f4799df38c18f9cd31cb5f7f57398/shared_library_with_ctypes/build.py#L6

This is the warning currently in place
https://github.com/pypa/setuptools/blob/v69.5.1/setuptools/dep_util.py#L5-L16.

**Comment by FirefoxMetzger** [comment]
Oh, I guess that comes with age. Would you be able to submit a PR to migrate away from the deprecated function?
